
apiVersion: v1
kind: Service
metadata:
  name: nginx-services
  namespace: default
spec:
  selector:
    app: nginx-deployment
  type: NodePort
  ports:
  - name: nginx
    protocol: TCP
    port: 8080
    targetPort: 8080
    