apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: default
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 7
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: webserver
