
apiVersion: v1
kind: Service
metadata:
  name: go-lang-services
  namespace: default
spec:
  selector:
    app: go-lang
  type: NodePort
  ports:
  - name: go
    protocol: TCP
    port: 8080
    targetPort: 8080
    