
apiVersion: v1
kind: Pod
metadata:
  name: "nginx-pod-v1"
  labels:
    app: "nginx"

spec:
  containers:
  - name: "nginx-pod-v1"
    image: "nginx:latest"
    ports:
    - containerPort: 80
      name: http
